#! /bin/bash
##
## Ban SSH password cracking attempts.
##
## Time-stamp: <2014-11-23 18:41:02 szi>
##

set -eu

FILE="$1"; shift

IP='[0-9]\+\.[0-9]\+\.[0-9]\+.[0-9]\+'
TZ=$(date '+%Y-%m-%d %H:%M:%S %z')

# Search failed SSH logins.
sed -n 's/.* sshd\[[0-9]*\]: Failed password .* \('"$IP"'\).*/\1/p' "$FILE" |
# Count the number of failures.
sort | uniq -c |
# Select all addresses with more than 3 failures.
awk '$1>3 {print $2}' |
# Remove the already banned.
grep -v -f <(iptables -S INPUT | awk '/BANIP/{sub(/\/.*/,"",$4);print $4}') |
# Report
tee >(
  read BAN < <(xargs echo)
  echo -en "${BAN:+Banning: $BAN\\n}" >&2
) |
# And ban the new assholes.
xargs -i iptables -A INPUT -s '{}' -m comment --comment "BANIP $TZ" -j DROP
